name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
 #    - name: Build main Docker image
 #      run: docker build . --file docker/php/Dockerfile --tag ammardev0/php:${{steps.vars.outputs.tag}}
    - name: Build php 7.1
      run: docker build . --file docker/php/Dockerfile71 --tag ammardev0/php:7.1
    - name: Push php7.1
      run: docker push ammardev0/php:7.1
    - name: Build php 7.3
      run: docker build . --file docker/php/Dockerfile73 --tag ammardev0/php:7.3
    - name: Push php7.3
      run: docker push ammardev0/php:7.3
    - name: Build php8.0
      run: docker build . --file docker/php/Dockerfile8 --tag ammardev0/php:8.0
    - name: Push php8.0
      run: docker push ammardev0/php:8.0
      #    - name: Push the tagged Docker image
      #      run: docker push ammardev0/php:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file docker/php/Dockerfile --tag ammardev0/php:latest
    - name: Push the latest Docker image
      run: docker push ammardev0/php:latest

